# Generated by Django 2.1.7 on 2019-03-22 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='gradeLevel',
            new_name='jobTitle',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='major',
        ),
    ]
